Mobile menu
Gopxfs/Portfolio pull request #10
Opened 2022-05-09 21:43 UTC by Gopxfs

Added mobile menu following the project requirements and minor changes:
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button or any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed.
- Styled the mobile menu section with CSS.
- Updated README.md information.

2022-05-09 22:22 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Gopxfs, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Great job on implementing the mobile menu in the first attempt 👏 
✔️ All linters are passing
✔️ Good PR title and description

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-09 22:22 UTC, sja-thedude commented on README.md
>  > Welcome to my portfolio!
- [ ] Kindly add a description to your readme so that anyone visiting your repo has an idea of what this project is about.

2022-05-09 22:22 UTC, sja-thedude commented on README.md
- [ ] Kindly add collaborator details, to have an idea of who all collaborated.

2022-05-09 22:22 UTC, sja-thedude commented on script.js
> +  menuOptions[i].addEventListener('click', toggleMenu);
- [ ] Kindly make sure to follow the font-weight for menu options.
- [ ] As you have noticed there are ( > ) on the right side of all the menu options. Kindly add all the three ( > ) at the respective place following the correct colour and size.

Your design:

<img width="458" alt="Screenshot 2022-05-10 at 1 01 41 AM" src="https://user-images.githubusercontent.com/70269507/167507634-6014fe06-351d-41ba-a6d4-480827f35e04.png">

Figma design:

<img width="315" alt="Screenshot 2022-05-10 at 1 02 59 AM" src="https://user-images.githubusercontent.com/70269507/167507648-db0225e1-6bcf-4a16-ba61-3d8e66c2b09a.png">

2022-05-10 01:05 UTC, roshan-bajgain approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lFHtqqh6orvAhbiGmy/giphy.gif"/>

### To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-05-10 01:09 UTC, merged